project:
  type: website
  preview:
    navigate: false
  resources:
    - outreach/news/data/**
    
    
website:
  site-url: https://saraseq-network.com
  favicon: image/network.png
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - icon: house
        href: index.qmd
    right:
      - href: about.qmd
        text: About me
      - href: research.qmd
        text: My Research
      - href: outreach.qmd
        text: Outreach
    tools:
      - text: Contact
        icon: link-45deg
        menu:
         - text: LinkedIn
           url:  https://www.linkedin.com/in/saraseq/
           icon: linkedin
         - text: GitHub
           url: https://github.com/saraseq-network
           icon: github
         - text: Email
           url: mailto:sequeira.23@osu.edu
           icon: envelope-plus-fill

  page-footer:  
    left: >-
     &#169; 2023 Sara C. Sequeira &#8729;   

format:
  html:
    highlight-style: atom-one
    theme: cosmo
    css: 
      - styles/styles.css
      - styles/research.css
      - styles/outreach-cards.css

    toc: true
    number-sections: false
    number-depth: 3
    
    
